# docker-compose.yml

version: '3.8'

services:
  postgres-db:
    image: docker.io/postgres:15 
    container_name: tcm_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-tcm_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-tcm_password}
      POSTGRES_DB: ${DB_NAME:-tcm_db_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: